export const nigerianStates = [
    'Abia', 'Adamawa', 'Akwa Ibom', 'Anambra', 'Bauchi', 'Bayelsa', 'Benue', 'Borno',
    'Cross River', 'Delta', 'Ebonyi', 'Edo', 'Ekiti', 'Enugu', 'FCT', 'Gombe',
    'Imo', 'Jigawa', 'Kaduna', 'Kano', 'Katsina', 'Kebbi', 'Kogi', 'Kwara',
    'Lagos', 'Nasarawa', 'Niger', 'Ogun', 'Ondo', 'Osun', 'Oyo', 'Plateau',
    'Rivers', 'Sokoto', 'Taraba', 'Yobe', 'Zamfara'
];

export const nigerianCities: Record<string, string[]> = {
    'Abia': ['Aba', 'Umuahia', 'Ohafia', 'Arochukwu', 'Isuikwuato'],
    'Adamawa': ['Yola', 'Mubi', 'Jimeta', 'Numan', 'Michika'],
    'Akwa Ibom': ['Uyo', 'Eket', 'Ikot Ekpene', 'Oron', 'Abak'],
    'Anambra': ['Awka', 'Onitsha', 'Nnewi', 'Ekwulobia', 'Ihiala'],
    'Bauchi': ['Bauchi', 'Azare', 'Misau', 'Jama\'are', 'Katagum'],
    'Bayelsa': ['Yenagoa', 'Brass', 'Ogbia', 'Sagbama', 'Nembe'],
    'Benue': ['Makurdi', 'Gboko', 'Otukpo', 'Katsina-Ala', 'Vandeikya'],
    'Borno': ['Maiduguri', 'Biu', 'Gwoza', 'Dikwa', 'Bama'],
    'Cross River': ['Calabar', 'Ikom', 'Ogoja', 'Ugep', 'Obudu'],
    'Delta': ['Asaba', 'Warri', 'Ughelli', 'Sapele', 'Agbor'],
    'Ebonyi': ['Abakaliki', 'Afikpo', 'Onueke', 'Edda', 'Ishielu'],
    'Edo': ['Benin City', 'Auchi', 'Uromi', 'Ekpoma', 'Igarra'],
    'Ekiti': ['Ado Ekiti', 'Ikere Ekiti', 'Ijero Ekiti', 'Efon-Alaaye', 'Omuo Ekiti'],
    'Enugu': ['Enugu', 'Nsukka', 'Agbani', 'Awgu', 'Udi'],
    'FCT': ['Abuja', 'Gwagwalada', 'Kuje', 'Bwari', 'Kwali'],
    'Gombe': ['Gombe', 'Kaltungo', 'Billiri', 'Bajoga', 'Dukku'],
    'Imo': ['Owerri', 'Orlu', 'Okigwe', 'Oguta', 'Mbaise'],
    'Jigawa': ['Dutse', 'Hadejia', 'Gumel', 'Kazaure', 'Ringim'],
    'Kaduna': ['Kaduna', 'Zaria', 'Kafanchan', 'Saminaka', 'Birnin Gwari'],
    'Kano': ['Kano', 'Rano', 'Gaya', 'Karaye', 'Bichi'],
    'Katsina': ['Katsina', 'Daura', 'Funtua', 'Malumfashi', 'Dutsin-Ma'],
    'Kebbi': ['Birnin Kebbi', 'Argungu', 'Yauri', 'Zuru', 'Jega'],
    'Kogi': ['Lokoja', 'Okene', 'Idah', 'Kabba', 'Anyigba'],
    'Kwara': ['Ilorin', 'Offa', 'Omu-Aran', 'Jebba', 'Lafiagi'],
    'Lagos': ['Ikeja', 'Lagos Island', 'Epe', 'Badagry', 'Ikorodu', 'Lekki', 'Victoria Island', 'Surulere', 'Yaba', 'Agege'],
    'Nasarawa': ['Lafia', 'Keffi', 'Akwanga', 'Nasarawa', 'Karu'],
    'Niger': ['Minna', 'Bida', 'Suleja', 'Kontagora', 'Lapai'],
    'Ogun': ['Abeokuta', 'Ijebu Ode', 'Sagamu', 'Ota', 'Ilaro'],
    'Ondo': ['Akure', 'Ondo', 'Owo', 'Ikare', 'Okitipupa'],
    'Osun': ['Osogbo', 'Ile-Ife', 'Ilesa', 'Ede', 'Ikirun'],
    'Oyo': ['Ibadan', 'Ogbomoso', 'Oyo', 'Iseyin', 'Saki'],
    'Plateau': ['Jos', 'Pankshin', 'Shendam', 'Barkin Ladi', 'Langtang'],
    'Rivers': ['Port Harcourt', 'Obio-Akpor', 'Bonny', 'Degema', 'Okrika'],
    'Sokoto': ['Sokoto', 'Tambuwal', 'Gwadabawa', 'Illela', 'Wurno'],
    'Taraba': ['Jalingo', 'Wukari', 'Bali', 'Takum', 'Gembu'],
    'Yobe': ['Damaturu', 'Potiskum', 'Gashua', 'Nguru', 'Geidam'],
    'Zamfara': ['Gusau', 'Kaura Namoda', 'Talata Mafara', 'Gummi', 'Anka']
};
